//
//  CRXSplashModels.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 22/06/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import QuickShotUtils

enum CRXSplashDestination: String {
  case onBoarding, login, signIn, inApp
}

struct CRXSplashRequest {
}

struct CRXSplashResponse {
  var destination: CRXSplashDestination?
  var transitionType: ViewControllerPresentationType?
}

struct CRXSplashViewModel {
  var destination: CRXSplashDestination?
  var transitionType: ViewControllerPresentationType?
}
