//
//  CRXOnBoardingInteractor.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 01/07/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CRXOnBoardingInteractorInput
{
  func doSomething(request: CRXOnBoardingRequest)
}

protocol CRXOnBoardingInteractorOutput
{
  func presentSomething(response: CRXOnBoardingResponse)
}

class CRXOnBoardingInteractor: CRXOnBoardingInteractorInput
{
  var output: CRXOnBoardingInteractorOutput!
  var worker: CRXOnBoardingWorker!
  
  // MARK: Business logic
  
  func doSomething(request: CRXOnBoardingRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = CRXOnBoardingWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = CRXOnBoardingResponse()
    output.presentSomething(response)
  }
}
