//
//  CRXOnBoardingInteractor.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 01/07/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation
import RxSwift

protocol CRXOnBoardingInteractorProtocol
{
//  func doSomething(request: CRXOnBoardingRequest)
  
  func getSlides() -> Observable<[CRXOnBoardingContent]>
  
  func triggeOnboardingFinish();
  
  func updateUserIsDone(_ isDone: Bool) -> Observable<Bool>;
}


class CRXOnBoardingInteractor: CRXOnBoardingInteractorProtocol
{
  var process: CRXOnBoardingProcess!;
  
  init(process: CRXOnBoardingProcess) {
    self.process = process;
  }
  
  // MARK: Business logic
  
  func getSlides() -> Observable<[CRXOnBoardingContent]> {
    var sliderPagesContent = [CRXOnBoardingContent]();
    
    var item1 = CRXOnBoardingContent();
    item1.titleText = "On Boarding Title 1";
    item1.descriptionText = "Bacon ipsum dolor amet tri-tip short ribs shankle, frankfurter ham beef spare ribs prosciutto filet mignon tongue pancetta jerky pork belly venison. Pastrami brisket meatball";
    item1.imageName = "img_slide_1";
    item1.bgColor = UIColor(hexString: "#D8941AFF");
    
    sliderPagesContent.append(item1);
    
    
    var item2 = CRXOnBoardingContent();
    item2.titleText = "On Boarding Title 2";
    item2.descriptionText = "Shankle short loin pork tail shank. Sirloin picanha beef pork belly. Meatball beef ribs shank, pork loin drumstick bacon fatback kielbasa frankfurter tenderloin beef biltong meatloaf";
    item2.imageName = "img_slide_2";
    item2.bgColor = UIColor(hexString: "#998CD9FF");
    
    sliderPagesContent.append(item2);
    
    var item3 = CRXOnBoardingContent();
    item3.titleText = "On Boarding Title 3";
    item3.descriptionText = "Shankle porchetta bacon, fatback bresaola kevin cow. Leberkas swine brisket venison, drumstick rump picanha capicola ball tip. Spare ribs pork chop ribeye cow.";
    item3.imageName = "img_slide_3";
    item3.bgColor = UIColor(hexString: "#8B81FFFF");
    
    sliderPagesContent.append(item3);
    
    var item4 = CRXOnBoardingContent();
    item4.titleText = "On Boarding Title 4";
    item4.descriptionText = "Beef ribs bresaola meatloaf, shankle swine biltong ribeye cupim tongue pig tri-tip ground round. Turducken turkey ball tip tongue jowl strip steak sausage pork drumstick shank doner.";
    item4.imageName = "img_slide_4";
    item4.bgColor = UIColor(hexString: "#8BAAFAFF");
    
    sliderPagesContent.append(item4);
    
    var item5 = CRXOnBoardingContent();
    item5.titleText = "On Boarding Title 5";
    item5.descriptionText = "Tongue shankle prosciutto tenderloin, bresaola tri-tip ground round sausage pig shoulder pork andouille.";
    item5.imageName = "img_slide_5";
    item5.bgColor = UIColor(hexString: "#FE8AB3FF");
    
    sliderPagesContent.append(item5);
    
    return Observable.just(sliderPagesContent);
  }
  
  func triggeOnboardingFinish(){
//    self.lazyInitializeBIProcess();
//    
//    worker.finishWelcomeWizard(userBIProcess);
  }
  
  func updateUserIsDone(_ isDone: Bool) -> Observable<Bool>
  {
    //apply delay before responding
    return process.updateUserOnboardingIsDone(isDone).subscribeOn(ConcurrentDispatchQueueScheduler(qos: .background)).observeOn(MainScheduler.instance).do(onNext: { (success) in
        //action success
    }, onError: { (error) in
        print("ERROR: \(error)");
    }, onCompleted: { 
        //completed action
    }, onSubscribe: { 
        //subscribed?
    }, onDispose: { 
        //cleanup
    })
    }
}
