//
//  CRXSplashConfigurator.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 22/06/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import QuickShotUtils

// MARK: Connect View, Interactor, and Presenter

extension CRXSplashViewController: CRXSplashPresenterOutput
{
}

extension CRXSplashInteractor: CRXSplashViewControllerOutput
{
}

extension CRXSplashPresenter: CRXSplashInteractorOutput
{
}

class CRXSplashConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: CRXSplashConfigurator
  {
    struct Static {
      static var instance: CRXSplashConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = CRXSplashConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: CRXSplashViewController)
  {
    let router = CRXSplashRouter()
    router.viewController = viewController
    
    let interactor = CRXSplashInteractor()
    
    let presenter = CRXSplashPresenter(interactor: interactor);
    presenter.output = viewController
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
