//
//  CRXSplashRouter.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 22/06/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import QuickShotUtils

enum CRXSplashDestination: String {
  case OnBoarding, Login, SignIn, InApp
}

protocol CRXSplashRouterInput
{
}

class CRXSplashRouter: CRXSplashRouterInput
{
  weak var viewController: CRXSplashViewController!
  
  // MARK: Navigation
  
  func navigateToNextScreen(destination: CRXSplashDestination?, transitionType: ViewControllerPresentationType?)
  {
    viewController.hideProgressIndicator();
    
    var destinationViewController: UIViewController? = nil
    
    if let dest = destination {
      switch(dest){
      case .OnBoarding:
        //destinationViewController = OnBoardingViewController();
        break;
      case .Login:
//        destinationViewController = RFLoginViewController()
        break;
      case .SignIn:
//        destinationViewController = RFSignInChooserViewController();
        break;
      case .InApp:
//        destinationViewController = RFRootViewController()
        break;
      }
    }
    
    viewController.transtitionToNextViewController(viewController, destinationViewController: destinationViewController, transitionType: transitionType);
  }
}
