//
//  SplashModels.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 22/06/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import QuickShotUtils

struct SplashRequest
{
}

struct SplashResponse
{
  var destination: SplashDestination?
  var transitionType: ViewControllerPresentationType?
}

struct SplashViewModel
{
}
