//
//  SplashInteractor.swift
//  CleanRxSwift
//
//  Created by Pedro Brito on 22/06/16.
//  Copyright (c) 2016 pedroml.brito. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import RxSwift

protocol SplashInteractorInput
{
//  func checkUserOnBoardingState(request: SplashRequest)
  
//  func updateUserIsDone() -> Observable<Bool>
}

protocol SplashInteractorOutput
{
  func presentSomething(response: SplashResponse)
}

class SplashInteractor: SplashInteractorInput
{
  var output: SplashInteractorOutput!
  
  var process: SplashProcess!;
  
  // MARK: Business logic
  
//  func checkUserOnBoardingState(request: SplashRequest){
//    self.updateUserIsDone();
//  }
  
  
  func updateUserIsDone() -> Observable<Bool>
  {
    self.lazyInitializeBIProcess();
    
    return process.checkIfOnboardingIsDone().delaySubscription(RxTimeInterval(5), scheduler: ConcurrentDispatchQueueScheduler(globalConcurrentQueueQOS: .Background)).observeOn(MainScheduler.instance).doOnError { error in
      print("ERROR: \(error)");
    }
  }
  
  func lazyInitializeBIProcess(){
    if(self.process == nil){
      self.process = SplashProcess();
    }
  }
}
